apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: syfosmpapirmottak
  namespace: default
  labels:
    team: "teamsykefravr"
spec:
  name: "syfosmpapirmottak"
  image: "repo.adeo.no:5443/syfo/syfosmpapirmottak:@@VERSION@@"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 700m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  vault:
    enabled: true
  ingress:
    disabled: false
  env:
  - name: KAFKA_BOOTSTRAP_SERVERS_URL
    value: {{KAFKA_BOOTSTRAP_SERVERS_URL}}
  - name: PERSON_V3_ENDPOINT_URL
    value: {{PERSON_V3_ENDPOINT_URL}}
  - name: ARBEIDSFORDELING_V1_ENDPOINT_URL
    value: {{ARBEIDSFORDELING_V1_ENDPOINT_URL}}
  - name: JOURNAL_FOER_INNGAAENDE_V1_URL
    value: {{JOURNAL_FOER_INNGAAENDE_V1_URL}}
  - name: SAF_URL
    value: {{SAF_URL}}
  - name: SECURITY_TOKEN_SERVICE_URL
    value: {{SECURITY_TOKEN_SERVICE_URL}}
  - name: AKTORREGISTER_V1_URL
    value: {{AKTORREGISTER_V1_URL}}
  - name: STS_URL
    value: {{STS_URL}}
