apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmpapirmottak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  vault:
    enabled: false
  webproxy: false
  env:
    - name: SAFGRAPHQL_URL
      value: https://saf.prod-fss-pub.nais.io/graphql
    - name: DOK_JOURNALFOERING_AIVEN_TOPIC
      value: teamdokumenthandtering.aapen-dok-journalfoering
    - name: HENT_DOKUMENT_URL
      value: https://saf.prod-fss-pub.nais.io
    - name: SAF_SCOPE
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: HELSENETT_SCOPE
      value: api://prod-fss.teamsykmelding.syfohelsenettproxy/.default
    - name: SYFOSMPAPIRREGLER_SCOPE
      value: api://prod-gcp.teamsykmelding.syfosmpapirregler/.default
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.prod-fss-pub.nais.io
    - name: PAPIRREGEL_ENDPOINT_URL
      value: https://syfosmpapirregler.intern.nav.no
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: SMGCP_PROXY_SCOPE
      value: api://prod-fss.teamsykmelding.smgcp-proxy/.default
    - name: SMGCP_PROXY_URL
      value: https://smgcp-proxy.prod-fss-pub.nais.io
    - name: OPPGAVE_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default