apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: syfosmpapirmottak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: teamsykmelding
  secretName: syfosmpapirmottak-unleash-api-token
  environment: development
---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmpapirmottak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      kafka:
        consumerGroup: syfosmpapirmottak-consumer
        threshold: 300
        topic: teamdokumenthandtering.aapen-dok-journalfoering
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 256Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: syfosmregler
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: smtss
        - application: syfohelsenettproxy
      external:
        - host: saf-q2.dev-fss-pub.nais.io
        - host: dokarkiv.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: oppgave.dev-fss-pub.nais.io
        - host: fat.kote.helsedirektoratet.no
        - host: teamsykmelding-unleash-api.nav.cloud.nais.io
  envFrom:
    - secret: syfosmpapirmottak-unleash-api-token
  env:
    - name: SAF_URL
      value: https://saf-q2.dev-fss-pub.nais.io
    - name: SAF_SCOPE
      value: api://dev-fss.teamdokumenthandtering.saf/.default
    - name: DOK_JOURNALFOERING_AIVEN_TOPIC
      value: teamdokumenthandtering.aapen-dok-journalfoering
    - name: HELSENETT_ENDPOINT_URL
      value: http://syfohelsenettproxy
    - name: HELSENETT_SCOPE
      value: api://dev-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: SYFOSMREGLER_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmregler/.default
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: OPPGAVE_URL
      value: https://oppgave.dev-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave/.default
    - name: SMTSS_API_SCOPE
      value: api://dev-gcp.teamsykmelding.smtss/.default
