apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmpapirmottak
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "docker.pkg.github.com/navikt/syfosmpapirmottak:{{tag}}"
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  ingresses:
    - "https://syfosmpapirmottak.nais.adeo.no"
  webproxy: true
  env:
    - name: ARBEIDSFORDELING_V1_ENDPOINT_URL
      value: https://app.adeo.no/norg2/ws/Arbeidsfordeling/v1
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: AKTORREGISTER_V1_URL
      value: https://app.adeo.no/aktoerregister/api/v1
    - name: SAFGRAPHQL_URL
      value: https://saf.nais.adeo.no/graphql
    - name: DISKRESJONSKODE_ENDPOINT_URL
      value: https://wasapp.adeo.no/tpsws/Diskresjonskode
    - name: DOK_JOURNALFOERING_V1_TOPIC
      value: aapen-dok-journalfoering-v1-p
    - name: HENT_DOKUMENT_URL
      value: https://saf.nais.adeo.no/
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: CLIENT_ID
      value: 9d4d6e11-1717-44f7-b76c-1a671847bb32
    - name: HELSENETTPROXY_ID
      value: b813133d-82b8-46ef-be96-3b903ea6c048
    - name: PAPIRREGEL_ID
      value: 77a0df77-18de-4bab-887a-ed65f5c44927
    - name: PERSON_V3_ENDPOINT_URL
      value: https://wasapp.adeo.no/tpsws/ws/Person/v3
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
