apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmpapirmottak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/syfosmpapirmottak/teamsykmelding
        mountPath: /secrets/default
      - kvPath: serviceuser/data/dev/srvsyfosmpapirmottak
        mountPath: /secrets/serviceuser
  ingresses:
    - "https://syfosmpapirmottak.nais.preprod.local"
  webproxy: true
  env:
    - name: SAFGRAPHQL_URL
      value: https://saf-q1.nais.preprod.local/graphql
    - name: DOK_JOURNALFOERING_V1_TOPIC
      value: aapen-dok-journalfoering-v1-q1
    - name: HENT_DOKUMENT_URL
      value: https://saf-q1.nais.preprod.local/
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: CLIENT_ID
      value: a99ce657-bce8-4f11-8dd6-5624038f4820
    - name: HELSENETTPROXY_ID
      value: c18eba24-f676-47db-9a97-3c66e9304aee
    - name: PAPIRREGEL_ID
      value: c35dd346-0d3d-4b68-b883-a324c0b1098d
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: DOK_ARKIV_URL
      value: https://dokarkiv-q1.nais.preprod.local/rest/journalpostapi/v1/journalpost
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave-q1.nais.preprod.local/api/v1/oppgaver
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.preprod.local
    - name: PAPIRREGEL_ENDPOINT_URL
      value: https://syfosmpapirregler.nais.preprod.local