apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmpapirmottak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfosmpapirmottak
        mountPath: /secrets/serviceuser
  ingresses:
    - "https://syfosmpapirmottak.nais.adeo.no"
  webproxy: true
  env:
    - name: SAFGRAPHQL_URL
      value: https://saf.intern.nav.no/graphql
    - name: DOK_JOURNALFOERING_AIVEN_TOPIC
      value: teamdokumenthandtering.aapen-dok-journalfoering
    - name: HENT_DOKUMENT_URL
      value: https://saf.intern.nav.no/
    - name: SAF_SCOPE
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: HELSENETT_SCOPE
      value: api://prod-fss.teamsykmelding.syfohelsenettproxy/.default
    - name: SYFOSMPAPIRREGLER_SCOPE
      value: api://prod-fss.teamsykmelding.syfosmpapirregler/.default
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.intern.nav.no/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.nais.adeo.no/api/v1/oppgaver
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.adeo.no
    - name: PAPIRREGEL_ENDPOINT_URL
      value: https://syfosmpapirregler.nais.adeo.no
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: KUHR_SAR_API_SCOPE
      value: api://prod-fss.teamkuhr.kuhr-sar-api/.default
    - name: KUHR_SAR_API_URL
      value: https://kuhr-sar-api.nais.adeo.no