apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmpapirmottak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      kafka:
        consumerGroup: syfosmpapirmottak-consumer
        threshold: 300
        topic: teamdokumenthandtering.aapen-dok-journalfoering-q1
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      rules:
        - application: syfosmregler
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: smtss
        - application: syfohelsenettproxy
      external:
        - host: saf.dev-fss-pub.nais.io
        - host: dokarkiv.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: oppgave-q1.dev-fss-pub.nais.io
  secureLogs:
    enabled: true
  env:
    - name: SAF_URL
      value: https://saf.dev-fss-pub.nais.io
    - name: SAF_SCOPE
      value: api://dev-fss.teamdokumenthandtering.saf-q1/.default
    - name: DOK_JOURNALFOERING_AIVEN_TOPIC
      value: teamdokumenthandtering.aapen-dok-journalfoering-q1
    - name: HELSENETT_ENDPOINT_URL
      value: http://syfohelsenettproxy
    - name: HELSENETT_SCOPE
      value: api://dev-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: SYFOSMREGLER_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmregler/.default
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: OPPGAVE_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
    - name: SMTSS_API_SCOPE
      value: api://dev-gcp.teamsykmelding.smtss/.default